name: cellular_automata
description: A library and platform for playing and experimenting with cellular automata.
version: 1.0.2
homepage: https://github.com/jimmyff/cellular_automata
author: Jimmy Forrester-Fellowes <jimmyff@jimmyff.uk>

environment:
  sdk: '>=2.0.0-dev.61.0 <3.0.0'

dependencies:
  logging: ^0.11.3+2

dev_dependencies:
  test: ^1.3.0