name: cellular_automata
description: A library and platform for playing and experimenting with cellular automata.
version: 1.0.0
homepage: https://github.com/jimmyff/cellular_automata
author: jimmyff <jimmyff@jimmyff.uk>

environment:
  sdk: '>=2.0.0-dev.63.0 <2.0.0'

dependencies:
  logging: '^0.11.3+1'

dev_dependencies:
  test: '^1.2.0'