name: ca_demos_web
description: Web demos utilising the cellular_automaton lib
version: 0.0.1
#homepage: https://www.example.com
author: jimmyff <jimmyff@jimmyff.uk>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  cellular_automaton:
    path: ../..

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter
