name: ca_demos_web
description: Web demos utilising the cellular_automata lib
version: 0.1.3
homepage: https://github.com/jimmyff/cellular_automata
author: jimmyff <jimmyff@jimmyff.uk>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  cellular_automata:
    path: ../..
  params: '^0.0.4'


dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  bwu_grinder_tasks: '^0.1.1-dev'

transformers:
- dart_to_js_script_rewriter
